use tms;

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket3` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket3 SELECT * FROM tms_sell_SellTicket WHERE DATEDIFF(curdate(),st_SellDate)>=1; 
DELETE FROM tms_sell_SellTicket WHERE DATEDIFF(curdate(),st_SellDate)>=1; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket7` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket7 SELECT * FROM tms_sell_SellTicket3 WHERE DATEDIFF(curdate(),st_SellDate)>=3; 
DELETE FROM tms_sell_SellTicket3 WHERE DATEDIFF(curdate(),st_SellDate)>=3; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket14` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket14 SELECT * FROM tms_sell_SellTicket7 WHERE DATEDIFF(curdate(),st_SellDate)>=7; 
DELETE FROM tms_sell_SellTicket7 WHERE DATEDIFF(curdate(),st_SellDate)>=7; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket30` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket30 SELECT * FROM tms_sell_SellTicket14 WHERE DATEDIFF(curdate(),st_SellDate)>=14; 
DELETE FROM tms_sell_SellTicket14 WHERE DATEDIFF(curdate(),st_SellDate)>=14; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket90` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket90 SELECT * FROM tms_sell_SellTicket30 WHERE DATEDIFF(curdate(),st_SellDate)>=30; 
DELETE FROM tms_sell_SellTicket30 WHERE DATEDIFF(curdate(),st_SellDate)>=30; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket180` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket180 SELECT * FROM tms_sell_SellTicket90 WHERE DATEDIFF(curdate(),st_SellDate)>=90; 
DELETE FROM tms_sell_SellTicket90 WHERE DATEDIFF(curdate(),st_SellDate)>=90; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket365` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket365 SELECT * FROM tms_sell_SellTicket180 WHERE DATEDIFF(curdate(),st_SellDate)>=180; 
DELETE FROM tms_sell_SellTicket180 WHERE DATEDIFF(curdate(),st_SellDate)>=180; 

CREATE TABLE IF NOT EXISTS `tms_sell_SellTicket730` (  
	`st_TicketID` varchar(20) NOT NULL ,                 
	`st_NoOfRunsID` varchar(20)  NULL ,                  
	`st_LineID` varchar(30)  NULL ,                       
	`st_NoOfRunsdate` char(10)  NULL ,                   
	`st_BeginStationTime` char(5)  NULL ,                 
	`st_StopStationTime` char(5)  NULL ,                  
	`st_Distance` decimal(12,2) NULL ,                     
	`st_BeginStationID` varchar(20)  NULL ,               
	`st_BeginStation` varchar(50)  NULL ,                 
	`st_FromStationID` varchar(20)  NULL ,              
	`st_FromStation` varchar(50)  NULL ,                 
	`st_ReachStationID` varchar(20)  NULL ,              
	`st_ReachStation` varchar(50)  NULL ,                 
	`st_EndStationID` varchar(20)  NULL ,                
	`st_EndStation` varchar(50)  NULL ,                   
	`st_SellPrice` decimal(12,1) NULL ,                    
	`st_SellPriceType` varchar(50)  NULL ,                 
	`st_ColleSellPriceType` varchar(2000)  NULL ,          
	`st_TotalMan` smallint NULL ,                         
	`st_FullPrice` decimal(12,1) NULL ,                   
	`st_HalfPrice` decimal(12,1) NULL ,                   
	`st_StandardPrice` decimal(12,1) NULL , 
	`st_BalancePrice` decimal(12,1) NULL ,             
	`st_ServiceFee` decimal(12,2) NULL ,                 
	`st_otherFee1` decimal(12,2) NULL ,
	`st_otherFee2` decimal(12,2) NULL ,
	`st_otherFee3` decimal(12,2) NULL ,
	`st_otherFee4` decimal(12,2) NULL ,
	`st_otherFee5` decimal(12,2) NULL ,
	`st_otherFee6` decimal(12,2) NULL ,
	`st_StationID` varchar(20)  NULL ,               
	`st_Station` varchar(50)  NULL ,                  
	`st_SellDate` char(10)  NULL ,                   
	`st_SellTime` char(5)  NULL ,                   
	`st_BusModelID` varchar(50)  NULL ,            
	`st_BusModel` varchar(50)  NULL ,              
	`st_SeatID` varchar(200)  NULL ,               
	`st_SellID` varchar(20)  NULL ,                
	`st_SellName` varchar(30)  NULL ,             
	`st_FreeSeats` smallint NULL ,                  
	`st_SafetyTicketNumber` smallint NULL ,         
	`st_SafetyTicketMoney` decimal(12,1) NULL ,      
	`st_TicketState` smallint NULL ,            
	`st_IsBalance` tinyint NULL ,                      
	`st_BalanceDateTime` datetime NULL ,           
	`st_AlterTicket` int NULL ,                    
	PRIMARY KEY (`st_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_sell_SellTicket730 SELECT * FROM tms_sell_SellTicket365 WHERE DATEDIFF(curdate(),st_SellDate)>=365; 
DELETE FROM tms_sell_SellTicket365 WHERE DATEDIFF(curdate(),st_SellDate)>=365; 

DELETE FROM tms_sell_SellTicket730 WHERE DATEDIFF(curdate(),st_SellDate)>=750;

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket3` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket3 SELECT * FROM tms_chk_CheckTicket WHERE DATEDIFF(curdate(),ct_CheckDate)>=1; 
DELETE FROM tms_chk_CheckTicket WHERE DATEDIFF(curdate(),ct_CheckDate)>=1; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket7` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket7 SELECT * FROM tms_chk_CheckTicket3 WHERE DATEDIFF(curdate(),ct_CheckDate)>=3; 
DELETE FROM tms_chk_CheckTicket3 WHERE DATEDIFF(curdate(),ct_CheckDate)>=3; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket14` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket14 SELECT * FROM tms_chk_CheckTicket7 WHERE DATEDIFF(curdate(),ct_CheckDate)>=7; 
DELETE FROM tms_chk_CheckTicket7 WHERE DATEDIFF(curdate(),ct_CheckDate)>=7; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket30` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket30 SELECT * FROM tms_chk_CheckTicket14 WHERE DATEDIFF(curdate(),ct_CheckDate)>=14; 
DELETE FROM tms_chk_CheckTicket14 WHERE DATEDIFF(curdate(),ct_CheckDate)>=14; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket90` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket90 SELECT * FROM tms_chk_CheckTicket30 WHERE DATEDIFF(curdate(),ct_CheckDate)>=30; 
DELETE FROM tms_chk_CheckTicket30 WHERE DATEDIFF(curdate(),ct_CheckDate)>=30; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket180` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket180 SELECT * FROM tms_chk_CheckTicket90 WHERE DATEDIFF(curdate(),ct_CheckDate)>=90; 
DELETE FROM tms_chk_CheckTicket90 WHERE DATEDIFF(curdate(),ct_CheckDate)>=90; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket365` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket365 SELECT * FROM tms_chk_CheckTicket180 WHERE DATEDIFF(curdate(),ct_CheckDate)>=180; 
DELETE FROM tms_chk_CheckTicket180 WHERE DATEDIFF(curdate(),ct_CheckDate)>=180; 

CREATE TABLE IF NOT EXISTS `tms_chk_CheckTicket730` ( 
	`ct_TicketID` varchar(20)  NOT NULL ,          
	`ct_NoOfRunsID` varchar(20)  NULL ,           
	`ct_LineID` varchar(30)  NULL ,               
	`ct_NoOfRunsdate` char(10)  NULL ,            
	`ct_BeginStationTime` char(5) NULL ,            
	`ct_StopStationTime` char(5)  NULL ,           
	`ct_Distance` decimal(12,2) NULL ,                     
	`ct_BeginStationID` varchar(20)  NULL ,       
	`ct_BeginStation` varchar(50)  NULL ,         
	`ct_FromStationID` varchar(20)  NULL ,       
	`ct_FromStation` varchar(50)  NULL ,          
	`ct_ReachStationID` varchar(20)  NULL ,        
	`ct_ReachStation` varchar(50)  NULL ,          
	`ct_EndStationID` varchar(20)  NULL ,         
	`ct_EndStation` varchar(50)  NULL ,           
	`ct_SellPrice` decimal(12,1) NULL ,            
	`ct_SellPriceType` varchar(50)  NULL ,         
	`ct_ColleSellPriceType` varchar(2000) NULL ,    
	`ct_TotalMan` smallint NULL ,                 
	`ct_FullPrice` decimal(12,1) NULL ,            
	`ct_HalfPrice` decimal(12,1) NULL ,            
	`ct_StandardPrice` decimal(12,1) NULL , 
	`ct_BalancePrice` decimal(12,1) NULL ,         
	`ct_ServiceFee` decimal(12,2) NULL ,          
	`ct_otherFee1` decimal(12,2) NULL ,
	`ct_otherFee2` decimal(12,2) NULL ,
	`ct_otherFee3` decimal(12,2) NULL ,
	`ct_otherFee4` decimal(12,2) NULL ,
	`ct_otherFee5` decimal(12,2) NULL ,
	`ct_otherFee6` decimal(12,2) NULL ,
	`ct_StationID` varchar(20)  NULL ,            
	`ct_Station` varchar(50)  NULL ,              
	`ct_SellDate` char(10)  NULL ,               
	`ct_SellTime` char(8)  NULL ,               
	`ct_BusModelID` varchar(20)  NULL ,        
	`ct_BusModel` varchar(50)  NULL ,          
     	`ct_BusID` varchar(20)  NULL ,            
     	`ct_BusNumber` varchar(20)  NULL ,       
	`ct_SeatID` varchar(200)  NULL ,          
     	`ct_SellID` varchar(20)  NULL ,             
	`ct_SellName` varchar(30)  NULL ,          
	`ct_FreeSeats` smallint NULL ,             
	`ct_SafetyPrice` smallint NULL ,             
	`ct_SafetyMoney` decimal(12,1) NULL ,       
	`ct_CheckTicketWindow` varchar(20) NULL ,   
	`ct_CheckerID` varchar(20)  NULL ,          
	`ct_Checker` varchar(30)  NULL ,            
	`ct_CheckDate` char(10)  NULL ,            
	`ct_CheckTime` char(5)  NULL ,             
	`ct_BalanceNO` varchar(50)  NULL ,
	`ct_IsBalance` tinyint NULL ,                      
	`ct_BalanceDateTime` datetime NULL ,           
	PRIMARY KEY (`ct_TicketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO tms_chk_CheckTicket730 SELECT * FROM tms_chk_CheckTicket365 WHERE DATEDIFF(curdate(),ct_CheckDate)>=365; 
DELETE FROM tms_chk_CheckTicket365 WHERE DATEDIFF(curdate(),ct_CheckDate)>=365; 

DELETE FROM tms_chk_CheckTicket730 WHERE DATEDIFF(curdate(),ct_CheckDate)>=750
